### PR TITLE
[WIP] Adds humanizing distances.

### LINKED ISSUE #152: [Request] Humanizing distances
### What I want to do
Humanize distances between two points (see Distance object https://docs.djangoproject.com/en/3.1/ref/contrib/gis/measure/#distance)

### Why it makes sense
For short distances it makes sense to have approximations in meters, for longer distances in kilometres or miles. It is also weird-looking to show the exact distance, e.g. 2392.324553 km. Then we have the locale issue where some countries prefer miles over kilometers.

I have been looking for some formulae online but can't find any best practices or libraries for this. I noticed that maps applications have this behaviour, but I can't find any specs to it.

Do you think such a function would be useful in humanize? Do you know of any specs/best practices? I am more than happy to do the implementation, if you think it is worth it, and if you can help with the full definition of this task.

### PR DESCRIPTION
**Pull request by calina-c**
Fixes #152.

Changes proposed in this pull request:
* add support for humanizing distances

Marking it as WIP for now. Can you @jmoiron give me some feedback regarding the code? I can add documentation and tests afterwards. This version includes:

- formatting for metric and imperial distances
- abbreviations (mi, km) and long names (miles, kilometers)
- singular and plural forms of units
- rounding to nearest 0.25 for floating values, nearest 25 for values larger than 100 (also closest 0.5 and 50 respectively)
- precision setting (no. of decimal points)
- support for a custom translations dictionary, until I can do more and implement locale. I've included a custom translation dictionary (ready to be used) that enables Commonwealth spelling.

Where I'm iffy:
- should I include django GIS Distance for type hinting Distances?
- should I drop the custom translation? Is it too confusing?

Otherwise I think it's a pretty nifty thing to have for devs working with Distance objects. 😄

### CODE REVIEW

**Comment by supRy** [comment]
I may be missing something, but this would add django as a dependency for this project, right?  That seems like a bad idea. Would it make sense to create a class in this code that replicates the django distance object? That way if you have a django distance object you could pass that in, if you don't you could create an object from humanize.

**Comment by calina-c** [comment]
@supRy I only added it for type hinting, which is why I asked :) To replicate the Django distance object how, exactly? Sort of like an interface?

**Comment by supRy** [comment]
@calina-c Sure, the use in this project would solely be for type hinting, but anyone using this will need to add a dependency to django to be able to use this.

By replicate, I mean create an distance class in this code that will eliminate a need for that user dependency, while keeping it possible to still use the django distance type too. In other words, a class which takes in a value for any unit and auto calculates equivalents for other units.

**Comment by calina-c** [comment]
closing this, since I don't have the time to implement the Distance class.

**Pull request closed without merging**
