### PR TITLE
Add intword processing for thousands

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

https://github.com/jmoiron/humanize/pull/187

### CODE REVIEW

**Comment by gliptak** [comment]
@hugovk @jordimas please approve running workflows

**Comment by gliptak** [comment]
@hugovk tests added. please approve workflows (again)

**Comment by hugovk** [comment]
Thank you!

**Comment by gliptak** [comment]
@hugovk other users might be in better position to work those translations

**Pull request merged**
